// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AgentService_CreateAgent_FullMethodName        = "/aos.api.v1.AgentService/CreateAgent"
	AgentService_GetAgent_FullMethodName           = "/aos.api.v1.AgentService/GetAgent"
	AgentService_ListAgents_FullMethodName         = "/aos.api.v1.AgentService/ListAgents"
	AgentService_UpdateAgent_FullMethodName        = "/aos.api.v1.AgentService/UpdateAgent"
	AgentService_DeleteAgent_FullMethodName        = "/aos.api.v1.AgentService/DeleteAgent"
	AgentService_StartAgent_FullMethodName         = "/aos.api.v1.AgentService/StartAgent"
	AgentService_StopAgent_FullMethodName          = "/aos.api.v1.AgentService/StopAgent"
	AgentService_RestartAgent_FullMethodName       = "/aos.api.v1.AgentService/RestartAgent"
	AgentService_GetAgentLogs_FullMethodName       = "/aos.api.v1.AgentService/GetAgentLogs"
	AgentService_StreamAgentLogs_FullMethodName    = "/aos.api.v1.AgentService/StreamAgentLogs"
	AgentService_GetAgentMetrics_FullMethodName    = "/aos.api.v1.AgentService/GetAgentMetrics"
	AgentService_StreamAgentMetrics_FullMethodName = "/aos.api.v1.AgentService/StreamAgentMetrics"
	AgentService_ExecuteCommand_FullMethodName     = "/aos.api.v1.AgentService/ExecuteCommand"
	AgentService_GetAgentEvents_FullMethodName     = "/aos.api.v1.AgentService/GetAgentEvents"
	AgentService_StreamAgentEvents_FullMethodName  = "/aos.api.v1.AgentService/StreamAgentEvents"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Create a new agent
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// Get agent by ID
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// List agents with filtering and pagination
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// Update an existing agent
	UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// Delete an agent
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*Empty, error)
	// Start an agent
	StartAgent(ctx context.Context, in *StartAgentRequest, opts ...grpc.CallOption) (*AgentActionResponse, error)
	// Stop an agent
	StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*AgentActionResponse, error)
	// Restart an agent
	RestartAgent(ctx context.Context, in *RestartAgentRequest, opts ...grpc.CallOption) (*AgentActionResponse, error)
	// Get agent logs
	GetAgentLogs(ctx context.Context, in *GetAgentLogsRequest, opts ...grpc.CallOption) (*GetAgentLogsResponse, error)
	// Stream agent logs (server-side streaming)
	StreamAgentLogs(ctx context.Context, in *StreamAgentLogsRequest, opts ...grpc.CallOption) (AgentService_StreamAgentLogsClient, error)
	// Get agent metrics
	GetAgentMetrics(ctx context.Context, in *GetAgentMetricsRequest, opts ...grpc.CallOption) (*AgentMetrics, error)
	// Stream agent metrics (server-side streaming)
	StreamAgentMetrics(ctx context.Context, in *StreamAgentMetricsRequest, opts ...grpc.CallOption) (AgentService_StreamAgentMetricsClient, error)
	// Execute command in agent
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	// Get agent events
	GetAgentEvents(ctx context.Context, in *GetAgentEventsRequest, opts ...grpc.CallOption) (*GetAgentEventsResponse, error)
	// Stream agent events (server-side streaming)
	StreamAgentEvents(ctx context.Context, in *StreamAgentEventsRequest, opts ...grpc.CallOption) (AgentService_StreamAgentEventsClient, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentService_CreateAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentService_GetAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentService_UpdateAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, AgentService_DeleteAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StartAgent(ctx context.Context, in *StartAgentRequest, opts ...grpc.CallOption) (*AgentActionResponse, error) {
	out := new(AgentActionResponse)
	err := c.cc.Invoke(ctx, AgentService_StartAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*AgentActionResponse, error) {
	out := new(AgentActionResponse)
	err := c.cc.Invoke(ctx, AgentService_StopAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RestartAgent(ctx context.Context, in *RestartAgentRequest, opts ...grpc.CallOption) (*AgentActionResponse, error) {
	out := new(AgentActionResponse)
	err := c.cc.Invoke(ctx, AgentService_RestartAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgentLogs(ctx context.Context, in *GetAgentLogsRequest, opts ...grpc.CallOption) (*GetAgentLogsResponse, error) {
	out := new(GetAgentLogsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgentLogs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamAgentLogs(ctx context.Context, in *StreamAgentLogsRequest, opts ...grpc.CallOption) (AgentService_StreamAgentLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StreamAgentLogs_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceStreamAgentLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_StreamAgentLogsClient interface {
	Recv() (*LogEntry, error)
	grpc.ClientStream
}

type agentServiceStreamAgentLogsClient struct {
	grpc.ClientStream
}

func (x *agentServiceStreamAgentLogsClient) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) GetAgentMetrics(ctx context.Context, in *GetAgentMetricsRequest, opts ...grpc.CallOption) (*AgentMetrics, error) {
	out := new(AgentMetrics)
	err := c.cc.Invoke(ctx, AgentService_GetAgentMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamAgentMetrics(ctx context.Context, in *StreamAgentMetricsRequest, opts ...grpc.CallOption) (AgentService_StreamAgentMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_StreamAgentMetrics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceStreamAgentMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_StreamAgentMetricsClient interface {
	Recv() (*AgentMetrics, error)
	grpc.ClientStream
}

type agentServiceStreamAgentMetricsClient struct {
	grpc.ClientStream
}

func (x *agentServiceStreamAgentMetricsClient) Recv() (*AgentMetrics, error) {
	m := new(AgentMetrics)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, AgentService_ExecuteCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgentEvents(ctx context.Context, in *GetAgentEventsRequest, opts ...grpc.CallOption) (*GetAgentEventsResponse, error) {
	out := new(GetAgentEventsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgentEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamAgentEvents(ctx context.Context, in *StreamAgentEventsRequest, opts ...grpc.CallOption) (AgentService_StreamAgentEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_StreamAgentEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceStreamAgentEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_StreamAgentEventsClient interface {
	Recv() (*AgentEvent, error)
	grpc.ClientStream
}

type agentServiceStreamAgentEventsClient struct {
	grpc.ClientStream
}

func (x *agentServiceStreamAgentEventsClient) Recv() (*AgentEvent, error) {
	m := new(AgentEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	// Create a new agent
	CreateAgent(context.Context, *CreateAgentRequest) (*Agent, error)
	// Get agent by ID
	GetAgent(context.Context, *GetAgentRequest) (*Agent, error)
	// List agents with filtering and pagination
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// Update an existing agent
	UpdateAgent(context.Context, *UpdateAgentRequest) (*Agent, error)
	// Delete an agent
	DeleteAgent(context.Context, *DeleteAgentRequest) (*Empty, error)
	// Start an agent
	StartAgent(context.Context, *StartAgentRequest) (*AgentActionResponse, error)
	// Stop an agent
	StopAgent(context.Context, *StopAgentRequest) (*AgentActionResponse, error)
	// Restart an agent
	RestartAgent(context.Context, *RestartAgentRequest) (*AgentActionResponse, error)
	// Get agent logs
	GetAgentLogs(context.Context, *GetAgentLogsRequest) (*GetAgentLogsResponse, error)
	// Stream agent logs (server-side streaming)
	StreamAgentLogs(*StreamAgentLogsRequest, AgentService_StreamAgentLogsServer) error
	// Get agent metrics
	GetAgentMetrics(context.Context, *GetAgentMetricsRequest) (*AgentMetrics, error)
	// Stream agent metrics (server-side streaming)
	StreamAgentMetrics(*StreamAgentMetricsRequest, AgentService_StreamAgentMetricsServer) error
	// Execute command in agent
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	// Get agent events
	GetAgentEvents(context.Context, *GetAgentEventsRequest) (*GetAgentEventsResponse, error)
	// Stream agent events (server-side streaming)
	StreamAgentEvents(*StreamAgentEventsRequest, AgentService_StreamAgentEventsServer) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) CreateAgent(context.Context, *CreateAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedAgentServiceServer) GetAgent(context.Context, *GetAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAgentServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentServiceServer) UpdateAgent(context.Context, *UpdateAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedAgentServiceServer) DeleteAgent(context.Context, *DeleteAgentRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgent not implemented")
}
func (UnimplementedAgentServiceServer) StartAgent(context.Context, *StartAgentRequest) (*AgentActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAgent not implemented")
}
func (UnimplementedAgentServiceServer) StopAgent(context.Context, *StopAgentRequest) (*AgentActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAgent not implemented")
}
func (UnimplementedAgentServiceServer) RestartAgent(context.Context, *RestartAgentRequest) (*AgentActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartAgent not implemented")
}
func (UnimplementedAgentServiceServer) GetAgentLogs(context.Context, *GetAgentLogsRequest) (*GetAgentLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentLogs not implemented")
}
func (UnimplementedAgentServiceServer) StreamAgentLogs(*StreamAgentLogsRequest, AgentService_StreamAgentLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAgentLogs not implemented")
}
func (UnimplementedAgentServiceServer) GetAgentMetrics(context.Context, *GetAgentMetricsRequest) (*AgentMetrics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentMetrics not implemented")
}
func (UnimplementedAgentServiceServer) StreamAgentMetrics(*StreamAgentMetricsRequest, AgentService_StreamAgentMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAgentMetrics not implemented")
}
func (UnimplementedAgentServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedAgentServiceServer) GetAgentEvents(context.Context, *GetAgentEventsRequest) (*GetAgentEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentEvents not implemented")
}
func (UnimplementedAgentServiceServer) StreamAgentEvents(*StreamAgentEventsRequest, AgentService_StreamAgentEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAgentEvents not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateAgent(ctx, req.(*UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StartAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StartAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartAgent(ctx, req.(*StartAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StopAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopAgent(ctx, req.(*StopAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RestartAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RestartAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RestartAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RestartAgent(ctx, req.(*RestartAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgentLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgentLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentLogs(ctx, req.(*GetAgentLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamAgentLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAgentLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamAgentLogs(m, &agentServiceStreamAgentLogsServer{stream})
}

type AgentService_StreamAgentLogsServer interface {
	Send(*LogEntry) error
	grpc.ServerStream
}

type agentServiceStreamAgentLogsServer struct {
	grpc.ServerStream
}

func (x *agentServiceStreamAgentLogsServer) Send(m *LogEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_GetAgentMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgentMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentMetrics(ctx, req.(*GetAgentMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamAgentMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAgentMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamAgentMetrics(m, &agentServiceStreamAgentMetricsServer{stream})
}

type AgentService_StreamAgentMetricsServer interface {
	Send(*AgentMetrics) error
	grpc.ServerStream
}

type agentServiceStreamAgentMetricsServer struct {
	grpc.ServerStream
}

func (x *agentServiceStreamAgentMetricsServer) Send(m *AgentMetrics) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgentEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgentEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentEvents(ctx, req.(*GetAgentEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamAgentEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAgentEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamAgentEvents(m, &agentServiceStreamAgentEventsServer{stream})
}

type AgentService_StreamAgentEventsServer interface {
	Send(*AgentEvent) error
	grpc.ServerStream
}

type agentServiceStreamAgentEventsServer struct {
	grpc.ServerStream
}

func (x *agentServiceStreamAgentEventsServer) Send(m *AgentEvent) error {
	return x.ServerStream.SendMsg(m)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aos.api.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _AgentService_CreateAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _AgentService_GetAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentService_ListAgents_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _AgentService_UpdateAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _AgentService_DeleteAgent_Handler,
		},
		{
			MethodName: "StartAgent",
			Handler:    _AgentService_StartAgent_Handler,
		},
		{
			MethodName: "StopAgent",
			Handler:    _AgentService_StopAgent_Handler,
		},
		{
			MethodName: "RestartAgent",
			Handler:    _AgentService_RestartAgent_Handler,
		},
		{
			MethodName: "GetAgentLogs",
			Handler:    _AgentService_GetAgentLogs_Handler,
		},
		{
			MethodName: "GetAgentMetrics",
			Handler:    _AgentService_GetAgentMetrics_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _AgentService_ExecuteCommand_Handler,
		},
		{
			MethodName: "GetAgentEvents",
			Handler:    _AgentService_GetAgentEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAgentLogs",
			Handler:       _AgentService_StreamAgentLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAgentMetrics",
			Handler:       _AgentService_StreamAgentMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAgentEvents",
			Handler:       _AgentService_StreamAgentEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
