// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: tenant.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TenantService_CreateTenant_FullMethodName       = "/aos.api.v1.TenantService/CreateTenant"
	TenantService_GetTenant_FullMethodName          = "/aos.api.v1.TenantService/GetTenant"
	TenantService_ListTenants_FullMethodName        = "/aos.api.v1.TenantService/ListTenants"
	TenantService_UpdateTenant_FullMethodName       = "/aos.api.v1.TenantService/UpdateTenant"
	TenantService_DeleteTenant_FullMethodName       = "/aos.api.v1.TenantService/DeleteTenant"
	TenantService_GetTenantQuota_FullMethodName     = "/aos.api.v1.TenantService/GetTenantQuota"
	TenantService_UpdateTenantQuota_FullMethodName  = "/aos.api.v1.TenantService/UpdateTenantQuota"
	TenantService_GetTenantUsage_FullMethodName     = "/aos.api.v1.TenantService/GetTenantUsage"
	TenantService_AddTenantMember_FullMethodName    = "/aos.api.v1.TenantService/AddTenantMember"
	TenantService_RemoveTenantMember_FullMethodName = "/aos.api.v1.TenantService/RemoveTenantMember"
	TenantService_ListTenantMembers_FullMethodName  = "/aos.api.v1.TenantService/ListTenantMembers"
	TenantService_UpdateTenantMember_FullMethodName = "/aos.api.v1.TenantService/UpdateTenantMember"
	TenantService_SuspendTenant_FullMethodName      = "/aos.api.v1.TenantService/SuspendTenant"
	TenantService_ActivateTenant_FullMethodName     = "/aos.api.v1.TenantService/ActivateTenant"
	TenantService_GetTenantStats_FullMethodName     = "/aos.api.v1.TenantService/GetTenantStats"
)

// TenantServiceClient is the client API for TenantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantServiceClient interface {
	// Create a new tenant
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// Get tenant by ID
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// List all tenants (admin only)
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error)
	// Update tenant
	UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// Delete tenant
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*Empty, error)
	// Get tenant quota
	GetTenantQuota(ctx context.Context, in *GetTenantQuotaRequest, opts ...grpc.CallOption) (*TenantQuota, error)
	// Update tenant quota
	UpdateTenantQuota(ctx context.Context, in *UpdateTenantQuotaRequest, opts ...grpc.CallOption) (*TenantQuota, error)
	// Get tenant resource usage
	GetTenantUsage(ctx context.Context, in *GetTenantUsageRequest, opts ...grpc.CallOption) (*TenantUsage, error)
	// Add member to tenant
	AddTenantMember(ctx context.Context, in *AddTenantMemberRequest, opts ...grpc.CallOption) (*TenantMember, error)
	// Remove member from tenant
	RemoveTenantMember(ctx context.Context, in *RemoveTenantMemberRequest, opts ...grpc.CallOption) (*Empty, error)
	// List tenant members
	ListTenantMembers(ctx context.Context, in *ListTenantMembersRequest, opts ...grpc.CallOption) (*ListTenantMembersResponse, error)
	// Update member role
	UpdateTenantMember(ctx context.Context, in *UpdateTenantMemberRequest, opts ...grpc.CallOption) (*TenantMember, error)
	// Suspend tenant
	SuspendTenant(ctx context.Context, in *SuspendTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// Activate tenant
	ActivateTenant(ctx context.Context, in *ActivateTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// Get tenant statistics
	GetTenantStats(ctx context.Context, in *GetTenantStatsRequest, opts ...grpc.CallOption) (*TenantStats, error)
}

type tenantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantServiceClient(cc grpc.ClientConnInterface) TenantServiceClient {
	return &tenantServiceClient{cc}
}

func (c *tenantServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_CreateTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_GetTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error) {
	out := new(ListTenantsResponse)
	err := c.cc.Invoke(ctx, TenantService_ListTenants_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_UpdateTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, TenantService_DeleteTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenantQuota(ctx context.Context, in *GetTenantQuotaRequest, opts ...grpc.CallOption) (*TenantQuota, error) {
	out := new(TenantQuota)
	err := c.cc.Invoke(ctx, TenantService_GetTenantQuota_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) UpdateTenantQuota(ctx context.Context, in *UpdateTenantQuotaRequest, opts ...grpc.CallOption) (*TenantQuota, error) {
	out := new(TenantQuota)
	err := c.cc.Invoke(ctx, TenantService_UpdateTenantQuota_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenantUsage(ctx context.Context, in *GetTenantUsageRequest, opts ...grpc.CallOption) (*TenantUsage, error) {
	out := new(TenantUsage)
	err := c.cc.Invoke(ctx, TenantService_GetTenantUsage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) AddTenantMember(ctx context.Context, in *AddTenantMemberRequest, opts ...grpc.CallOption) (*TenantMember, error) {
	out := new(TenantMember)
	err := c.cc.Invoke(ctx, TenantService_AddTenantMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) RemoveTenantMember(ctx context.Context, in *RemoveTenantMemberRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, TenantService_RemoveTenantMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) ListTenantMembers(ctx context.Context, in *ListTenantMembersRequest, opts ...grpc.CallOption) (*ListTenantMembersResponse, error) {
	out := new(ListTenantMembersResponse)
	err := c.cc.Invoke(ctx, TenantService_ListTenantMembers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) UpdateTenantMember(ctx context.Context, in *UpdateTenantMemberRequest, opts ...grpc.CallOption) (*TenantMember, error) {
	out := new(TenantMember)
	err := c.cc.Invoke(ctx, TenantService_UpdateTenantMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) SuspendTenant(ctx context.Context, in *SuspendTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_SuspendTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) ActivateTenant(ctx context.Context, in *ActivateTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, TenantService_ActivateTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenantStats(ctx context.Context, in *GetTenantStatsRequest, opts ...grpc.CallOption) (*TenantStats, error) {
	out := new(TenantStats)
	err := c.cc.Invoke(ctx, TenantService_GetTenantStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantServiceServer is the server API for TenantService service.
// All implementations must embed UnimplementedTenantServiceServer
// for forward compatibility
type TenantServiceServer interface {
	// Create a new tenant
	CreateTenant(context.Context, *CreateTenantRequest) (*Tenant, error)
	// Get tenant by ID
	GetTenant(context.Context, *GetTenantRequest) (*Tenant, error)
	// List all tenants (admin only)
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error)
	// Update tenant
	UpdateTenant(context.Context, *UpdateTenantRequest) (*Tenant, error)
	// Delete tenant
	DeleteTenant(context.Context, *DeleteTenantRequest) (*Empty, error)
	// Get tenant quota
	GetTenantQuota(context.Context, *GetTenantQuotaRequest) (*TenantQuota, error)
	// Update tenant quota
	UpdateTenantQuota(context.Context, *UpdateTenantQuotaRequest) (*TenantQuota, error)
	// Get tenant resource usage
	GetTenantUsage(context.Context, *GetTenantUsageRequest) (*TenantUsage, error)
	// Add member to tenant
	AddTenantMember(context.Context, *AddTenantMemberRequest) (*TenantMember, error)
	// Remove member from tenant
	RemoveTenantMember(context.Context, *RemoveTenantMemberRequest) (*Empty, error)
	// List tenant members
	ListTenantMembers(context.Context, *ListTenantMembersRequest) (*ListTenantMembersResponse, error)
	// Update member role
	UpdateTenantMember(context.Context, *UpdateTenantMemberRequest) (*TenantMember, error)
	// Suspend tenant
	SuspendTenant(context.Context, *SuspendTenantRequest) (*Tenant, error)
	// Activate tenant
	ActivateTenant(context.Context, *ActivateTenantRequest) (*Tenant, error)
	// Get tenant statistics
	GetTenantStats(context.Context, *GetTenantStatsRequest) (*TenantStats, error)
	mustEmbedUnimplementedTenantServiceServer()
}

// UnimplementedTenantServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTenantServiceServer struct {
}

func (UnimplementedTenantServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedTenantServiceServer) GetTenant(context.Context, *GetTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedTenantServiceServer) ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedTenantServiceServer) UpdateTenant(context.Context, *UpdateTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenant not implemented")
}
func (UnimplementedTenantServiceServer) DeleteTenant(context.Context, *DeleteTenantRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedTenantServiceServer) GetTenantQuota(context.Context, *GetTenantQuotaRequest) (*TenantQuota, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantQuota not implemented")
}
func (UnimplementedTenantServiceServer) UpdateTenantQuota(context.Context, *UpdateTenantQuotaRequest) (*TenantQuota, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenantQuota not implemented")
}
func (UnimplementedTenantServiceServer) GetTenantUsage(context.Context, *GetTenantUsageRequest) (*TenantUsage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantUsage not implemented")
}
func (UnimplementedTenantServiceServer) AddTenantMember(context.Context, *AddTenantMemberRequest) (*TenantMember, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTenantMember not implemented")
}
func (UnimplementedTenantServiceServer) RemoveTenantMember(context.Context, *RemoveTenantMemberRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTenantMember not implemented")
}
func (UnimplementedTenantServiceServer) ListTenantMembers(context.Context, *ListTenantMembersRequest) (*ListTenantMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTenantMembers not implemented")
}
func (UnimplementedTenantServiceServer) UpdateTenantMember(context.Context, *UpdateTenantMemberRequest) (*TenantMember, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenantMember not implemented")
}
func (UnimplementedTenantServiceServer) SuspendTenant(context.Context, *SuspendTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendTenant not implemented")
}
func (UnimplementedTenantServiceServer) ActivateTenant(context.Context, *ActivateTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateTenant not implemented")
}
func (UnimplementedTenantServiceServer) GetTenantStats(context.Context, *GetTenantStatsRequest) (*TenantStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantStats not implemented")
}
func (UnimplementedTenantServiceServer) mustEmbedUnimplementedTenantServiceServer() {}

// UnsafeTenantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantServiceServer will
// result in compilation errors.
type UnsafeTenantServiceServer interface {
	mustEmbedUnimplementedTenantServiceServer()
}

func RegisterTenantServiceServer(s grpc.ServiceRegistrar, srv TenantServiceServer) {
	s.RegisterService(&TenantService_ServiceDesc, srv)
}

func _TenantService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).ListTenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_UpdateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).UpdateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_UpdateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).UpdateTenant(ctx, req.(*UpdateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_DeleteTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).DeleteTenant(ctx, req.(*DeleteTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenantQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenantQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenantQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenantQuota(ctx, req.(*GetTenantQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_UpdateTenantQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).UpdateTenantQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_UpdateTenantQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).UpdateTenantQuota(ctx, req.(*UpdateTenantQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenantUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenantUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenantUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenantUsage(ctx, req.(*GetTenantUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_AddTenantMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTenantMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).AddTenantMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_AddTenantMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).AddTenantMember(ctx, req.(*AddTenantMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_RemoveTenantMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTenantMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).RemoveTenantMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_RemoveTenantMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).RemoveTenantMember(ctx, req.(*RemoveTenantMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_ListTenantMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).ListTenantMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_ListTenantMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).ListTenantMembers(ctx, req.(*ListTenantMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_UpdateTenantMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).UpdateTenantMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_UpdateTenantMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).UpdateTenantMember(ctx, req.(*UpdateTenantMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_SuspendTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).SuspendTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_SuspendTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).SuspendTenant(ctx, req.(*SuspendTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_ActivateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).ActivateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_ActivateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).ActivateTenant(ctx, req.(*ActivateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenantStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenantStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenantStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenantStats(ctx, req.(*GetTenantStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantService_ServiceDesc is the grpc.ServiceDesc for TenantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aos.api.v1.TenantService",
	HandlerType: (*TenantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _TenantService_CreateTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _TenantService_GetTenant_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _TenantService_ListTenants_Handler,
		},
		{
			MethodName: "UpdateTenant",
			Handler:    _TenantService_UpdateTenant_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _TenantService_DeleteTenant_Handler,
		},
		{
			MethodName: "GetTenantQuota",
			Handler:    _TenantService_GetTenantQuota_Handler,
		},
		{
			MethodName: "UpdateTenantQuota",
			Handler:    _TenantService_UpdateTenantQuota_Handler,
		},
		{
			MethodName: "GetTenantUsage",
			Handler:    _TenantService_GetTenantUsage_Handler,
		},
		{
			MethodName: "AddTenantMember",
			Handler:    _TenantService_AddTenantMember_Handler,
		},
		{
			MethodName: "RemoveTenantMember",
			Handler:    _TenantService_RemoveTenantMember_Handler,
		},
		{
			MethodName: "ListTenantMembers",
			Handler:    _TenantService_ListTenantMembers_Handler,
		},
		{
			MethodName: "UpdateTenantMember",
			Handler:    _TenantService_UpdateTenantMember_Handler,
		},
		{
			MethodName: "SuspendTenant",
			Handler:    _TenantService_SuspendTenant_Handler,
		},
		{
			MethodName: "ActivateTenant",
			Handler:    _TenantService_ActivateTenant_Handler,
		},
		{
			MethodName: "GetTenantStats",
			Handler:    _TenantService_GetTenantStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenant.proto",
}
